require 'ostruct'
require 'httparty'
require 'json'

require File.join('starcraft2', 'errors', 'missing_arguments_error')
require File.join('starcraft2', 'utils')
require File.join('starcraft2', 'icon')
require File.join('starcraft2', 'client')
require File.join('starcraft2', 'achievement')
require File.join('starcraft2', 'reward')
require File.join('starcraft2', 'ladder')
require File.join('starcraft2', 'member')
require File.join('starcraft2', 'character')
require File.join('starcraft2', 'profile', 'match')
require File.join('starcraft2', 'profile', 'swarm_race')
require File.join('starcraft2', 'profile', 'swarm_levels')
require File.join('starcraft2', 'profile', 'career')
require File.join('starcraft2', 'profile', 'campaign')
require File.join('starcraft2', 'profile', 'season')
require File.join('starcraft2', 'profile', 'stats')
require File.join('starcraft2', 'profile', 'rewards')
require File.join('starcraft2', 'profile', 'achievements')
require File.join('starcraft2', 'profile', 'points')
require File.join('starcraft2', 'profile', 'achievement_item')
require File.join('starcraft2', 'profile')
